<div class="title prepend-top">Запрос на восстановление доступа</div>
<?php if (!empty($this->message)):?>
    <div class="error text-center"><?=$this->message?></div>
<?php endif;?>
<div class="login-form-wrap layout-center">
    <form class="login" method="post" action="/default/password-recovery/request-form">
    <del><input type="hidden" value="1" name="do" /></del>
        <div>
            <div>
                <label for="login">Логин</label>
                <input type="text" name="login" id="login" value="" />
            </div>
            <div>
                <label for="email">E-mail</label>
                <input type="text" name="email" id="email" value="" />
            </div>
            <div>
                <input type="submit" value="Далее" />
            </div>
        </div>
    </form>
</div>