<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10.0pt;
        }
        div.wrapper {
            width: 700px;
            margin: 0  auto;
        }
        table {
            border-collapse: collapse;
        }
        td, th {
            padding: 2px;
            border: 1px solid;
            font-weight: normal;
        }
        .sign {
            background: url('/images/director_sign.png') no-repeat 50% 20%;
            height: 40px;
            padding-top: 40px;
        }
        .half-width {
            display: inline-table;
            width: 345px;
        }
        .stamp {
            background: url('/images/director_stamp.png') no-repeat 20% 100%;
        }
    </style>
</head>
<body>
<div class="wrapper stamp">
    <p><b><u>ООО "Полезные ресурсы"</u></b></p>
    <p><b>Адрес: 143900, Московская область, Балашихинский район, г. Балашиха, мкр. 1 Мая, д.21</b></p>
    <br />
    <div style="text-align: center; font-size:14.0pt;">
        <b>АКТ № <?=$this->act_number; ?> от <?=$this->act_date; ?> г.</b>
    </div>
    <br />
    <p>Заказчик: <?=$this->customer_name; ?></p>
    <br />
    <table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <th>№</th>
            <th>Наименование работы (услуги)</th>
            <th>Ед.&nbsp;изм.</th>
            <th>Кол-во</th>
            <th>Цена</th>
            <th>Сумма</th>
        </tr>
        <tr>
            <td>1</td>
            <td>Предоставление доступа к автоматизированной системе "e-head" в сентябре 2010 года</td>
            <td align="center">&lt;&gt;</td>
            <td align="center">1</td>
            <td align="right"><?=$this->price; ?>,00</td>
            <td align="right"><?=$this->price; ?>,00</td>
        </tr>
        <tr>
            <td colspan="5" style="text-align: right; border: none;"><b>Итого:</b></td>
            <td align="right"><b><?=$this->price; ?>,00</b></td>
        </tr>
        <tr>
            <td colspan="5" style="text-align: right; border: none;"><b>Без налога (НДС):</b></td>
            <td align="right">-</td>
        </tr>
        <tr>
            <td colspan="5" style="text-align: right; border: none;"><b>Всего к оплате:</b></td>
            <td align="right"><b><?=$this->price; ?>,00</b></td>
        </tr>
    </table>
    <p>Всего оказано услуг на сумму: <?=$this->price_letter; ?> 00 копеек. Без НДС.</p>
    <p>Вышеперечисленные услуги выполнены полностью и в срок. Заказчик претензий по объему, качеству и срокам оказания услуг не имеет.</p>
    <div class="sign half-width">Исполнитель: ___________________________
    <br /><br /><br /><br /><br /><span style="margin-left: 100px;">М.П.</span></div>
    <div class="half-width">Заказчик: ___________________________
    <br /><br /><br /><br /><br /><span style="margin-left: 100px;">М.П.</span></div>
    <br /><br />
</div>
</body>
</html>
<?php // echo '<!-- <pre>'; var_dump($this); echo '</pre> -->'; ?>